package dukono.minidsl.processor.generator;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import com.squareup.javapoet.WildcardTypeName;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the AnchorOperationsLogical class for a DSL domain. Extends
 * AnchorOperationsBase and adds logical operations (open, close).
 */
public class AnchorOperationsLogicalGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final TypeSpec typeSpec = this.generateAsNestedClass(context);

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = GeneratedClassNames.ANCHOR_OPERATIONS_LOGICAL.getClassName();
		final String baseClassName = GeneratedClassNames.ANCHOR_OPERATIONS.getClassName();

		// Type variable H extends AnchorHolderMainLogical
		final TypeVariableName h = TypeVariableName.get("H",
				ParameterizedTypeName.get(ClassName.get(dukono.minidsl.AnchorHolderMainLogical.class),
						WildcardTypeName.subtypeOf(Object.class), WildcardTypeName.subtypeOf(Object.class),
						TypeVariableName.get("H"), WildcardTypeName.subtypeOf(Object.class)));

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).addTypeVariable(h)
				.superclass(ParameterizedTypeName.get(ClassName.bestGuess(baseClassName), TypeVariableName.get("H")))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorOperationsLogical class for $L domain.\n", context.getDomainName())
				.addJavadoc("Extends $L and adds logical operations (open, close).\n", baseClassName)
				.addJavadoc("\n@generated by DslProcessor\n");

		// Add open() method
		final MethodSpec openMethod = MethodSpec.methodBuilder("open").addModifiers(Modifier.PUBLIC)
				.returns(TypeVariableName.get("H")).addJavadoc("Opens a logical group (parenthesis).\n")
				.addJavadoc("@return this holder for chaining\n")
				.addStatement("return this.create($T.OPEN)", ClassName.get(dukono.minidsl.Query.class)).build();

		// Add close() method
		final MethodSpec closeMethod = MethodSpec.methodBuilder("close").addModifiers(Modifier.PUBLIC)
				.returns(TypeVariableName.get("H")).addJavadoc("Closes a logical group (parenthesis).\n")
				.addJavadoc("@return this holder for chaining\n")
				.addStatement("return this.create($T.CLOSE)", ClassName.get(dukono.minidsl.Query.class)).build();

		classBuilder.addMethod(openMethod);
		classBuilder.addMethod(closeMethod);

		return classBuilder.build();
	}
}
