package dukono.minidsl.processor.generator;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import com.squareup.javapoet.WildcardTypeName;
import dukono.minidsl.annotation.DslOperation;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.Collection;

/**
 * Generates the AnchorOperationsBase class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public class VehicleAnchorOperations<H extends AnchorHolderMain<?, ?, H, ?>> extends AnchorOperationsBasic<H> {
 * 
 * 	public H equalTo(Object arg) {
 * 		return this.create(Query.from(this.getName(), "eq", arg));
 * 	}
 * }
 * </pre>
 */
public class AnchorOperationsGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final TypeSpec typeSpec = this.generateAsNestedClass(context);

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = "AnchorOperations";

		// Type variable H
		final TypeVariableName h = TypeVariableName.get("H",
				ParameterizedTypeName.get(ClassName.get("dukono.minidsl", "AnchorHolderMain"),
						WildcardTypeName.subtypeOf(Object.class), WildcardTypeName.subtypeOf(Object.class),
						TypeVariableName.get("H"), WildcardTypeName.subtypeOf(Object.class)));

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).addTypeVariable(h)
				.superclass(ParameterizedTypeName.get(ClassName.get("dukono.minidsl", "AnchorOperationsBasic"),
						TypeVariableName.get("H")))
				.addJavadoc("Generated AnchorOperations class for $L domain.\n", context.getDomainName())
				.addJavadoc("\n").addJavadoc("Contains all operation methods that can be called on fields.\n")
				.addJavadoc("\n").addJavadoc("@generated by DslProcessor\n");

		// Add method for each operation
		for (final DslOperation operation : context.getOperations()) {
			final MethodSpec method = this.generateOperationMethod(operation, h);
			classBuilder.addMethod(method);
		}

		return classBuilder.build();
	}

	private MethodSpec generateOperationMethod(final DslOperation operation, final TypeVariableName h) {
		final String methodName = operation.name();

		final MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(methodName).addModifiers(Modifier.PUBLIC)
				.returns(TypeVariableName.get("H"));

		if (!operation.description().isEmpty()) {
			methodBuilder.addJavadoc("$L\n", operation.description());
		}

		switch (operation.type()) {
			case WITH_ARG :
				// Operation with pattern: getName + operation + arg
				// Example: equalTo(Object arg)
				methodBuilder.addParameter(Object.class, "arg");
				methodBuilder.addStatement("return this.create($T.from(this.getName(), $S, arg))",
						ClassName.get("dukono.minidsl", "Query"), operation.operator());
				break;

			case WITH_LIST :
				// Operation with pattern: getName + operation + list
				// Example: inValues(Collection<Object> arg)
				methodBuilder.addParameter(
						ParameterizedTypeName.get(ClassName.get(Collection.class), ClassName.get(Object.class)), "arg");
				methodBuilder.addStatement("return this.create($T.from(this.getName(), $S, this.listFormatting(arg)))",
						ClassName.get("dukono.minidsl", "Query"), operation.operator());
				break;

			case WITH_EMPTY :
				// Operation with pattern: getName + operation + empty
				// Example: isNotNull()
				methodBuilder.addStatement("return this.create($T.from(this.getName(), $S, $T.empty()))",
						ClassName.get("dukono.minidsl", "Query"), operation.operator(),
						ClassName.get("java.util", "Optional"));
				break;

			case JUST_ADD :
				// Operation with pattern: getName + null + empty
				// Example: justAdd()
				methodBuilder.addStatement("return this.create($T.from(this.getName(), null, $T.empty()))",
						ClassName.get("dukono.minidsl", "Query"), ClassName.get("java.util", "Optional"));
				break;
		}

		return methodBuilder.build();
	}
}
