package dukono.minidsl.processor.generator;

import java.io.IOException;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import dukono.minidsl.processor.DslContext;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;

/**
 * Generates the AnchorOne class for a DSL domain. Used for individual items
 * within lists.
 */
public class AnchorOneGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String className = context.getDomainName() + "AnchorOne";
		final String fieldsClassName = context.getFieldsClassName();
		final String operationsOneClassName = context.getDomainName() + "AnchorOperationsOne";
		final String dtoClassName = context.getDtoClass();

		final TypeVariableName t = TypeVariableName.get("T");

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC)
				.addTypeVariable(t)
				.superclass(ParameterizedTypeName.get(ClassName.get("dukono.minidsl", "AnchorHolderOne"),
						ClassName.get(context.getPackageName(), fieldsClassName), ClassName.bestGuess(dtoClassName),
						ParameterizedTypeName
								.get(ClassName.get(context.getPackageName(), className), TypeVariableName.get("T")),
						TypeVariableName.get("T"),
						ParameterizedTypeName.get(ClassName.get(context.getPackageName(), operationsOneClassName),
								ParameterizedTypeName.get(ClassName.get(context.getPackageName(), className),
										TypeVariableName.get("T")),
								TypeVariableName.get("T"))))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorOne class for $L domain.\n", context.getDomainName())
				.addJavadoc("Represents a single item within a list for DSL operations.\n")
				.addJavadoc("\n@param <T> the type of the list item\n").addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super(new $T<$T>() {}, new $T(), new $T<$L<$T<T>, T>>() {})",
						ClassName.get("com.google.common.reflect", "TypeToken"), ClassName.bestGuess(dtoClassName),
						ClassName.get(context.getPackageName(), fieldsClassName),
						ClassName.get("com.google.common.reflect", "TypeToken"), operationsOneClassName,
						ClassName.get(context.getPackageName(), className))
				.build();

		classBuilder.addMethod(constructor);

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}
}
