package dukono.minidsl.processor.generator;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the AnchorMain class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public class VehicleAnchor
 * 		extends
 * 			AnchorHolderMainActions<VehicleFields, DtoString, VehicleAnchor, VehicleAnchorOperations<VehicleAnchor>> {
 * 
 * 	public VehicleAnchor() {
 * 		super(new TypeToken<DtoString>() {
 * 		}, new TypeToken<VehicleList<?>>() {
 * 		}, new TypeToken<VehicleAnchor>() {
 * 		}, new TypeToken<VehicleAnchorOperations<VehicleAnchor>>() {
 * 		}, new VehicleFields());
 * 	}
 * }
 * </pre>
 */
public class AnchorMainGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String className = context.getAnchorClassName();
		final String fieldsClass = context.getFieldsClassName();
		final String operationsClass = context.getAnchorOperationsClassName();

		// Get DTO class name properly
		final ClassName dtoClassName = ClassName.get(context.getDtoPackageName(), context.getDtoSimpleName());

		// Use AnchorHolderMain as base class (always includes actions and logical)
		final ClassName baseClass = ClassName.get(dukono.minidsl.AnchorHolderMain.class);

		final ClassName anchorClassName = ClassName.get(context.getPackageName(), className);

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC)
				.superclass(ParameterizedTypeName.get(baseClass, ClassName.get(context.getPackageName(), fieldsClass),
						dtoClassName, anchorClassName,
						ParameterizedTypeName.get(ClassName.get(context.getPackageName(), operationsClass),
								anchorClassName)))
				.addJavadoc("Generated Anchor class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("This is the main entry point for building queries.\n").addJavadoc("\n")
				.addJavadoc("Example:\n").addJavadoc("<pre>\n").addJavadoc("new $L()\n", className)
				.addJavadoc("    .field(f -> f.FIELD_NAME).equalTo(value)\n").addJavadoc("    .other()\n")
				.addJavadoc("    .getDto();\n").addJavadoc("</pre>\n").addJavadoc("\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement(
						"super(\n" + "    new $T<$T>() {},\n" + "    new $T<$LAnchorList<?>>() {},\n"
								+ "    new $T<$T<$T>>() {},\n" + "    new $T()\n" + ")",
						ClassName.get(com.google.common.reflect.TypeToken.class), dtoClassName,
						ClassName.get(com.google.common.reflect.TypeToken.class), context.getDomainName(),
						ClassName.get(com.google.common.reflect.TypeToken.class),
						ClassName.get(context.getPackageName(), operationsClass), anchorClassName,
						ClassName.get(context.getPackageName(), fieldsClass))
				.build();

		classBuilder.addMethod(constructor);

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = GeneratedClassNames.ANCHOR_MAIN.getClassName();
		final String fieldsClass = GeneratedClassNames.FIELDS.getClassName();
		final String operationsClass = GeneratedClassNames.ANCHOR_OPERATIONS.getClassName();

		// Get DTO class name properly - could be in different package or user-provided
		final ClassName dtoClassName = context.getDtoClassName();

		// Use AnchorHolderMainActions as base class (always includes actions and
		// logical)
		final ClassName baseClass = ClassName.get(dukono.minidsl.AnchorHolderMain.class);

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.superclass(ParameterizedTypeName.get(baseClass, ClassName.bestGuess(fieldsClass), dtoClassName,
						ClassName.bestGuess(className),
						ParameterizedTypeName.get(ClassName.bestGuess(operationsClass),
								ClassName.bestGuess(className))))
				.addJavadoc("Generated Anchor class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("This is the main entry point for building queries.\n").addJavadoc("\n")
				.addJavadoc("Example:\n").addJavadoc("<pre>\n").addJavadoc("new $L()\n", className)
				.addJavadoc("    .field(f -> f.FIELD_NAME).equalTo(value)\n").addJavadoc("    .other()\n")
				.addJavadoc("    .getDto();\n").addJavadoc("</pre>\n").addJavadoc("\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement(
						"super(\n" + "    new $T<$T>() {},\n" + "    new $T<AnchorList<?>>() {},\n"
								+ "    new $T<$L<$L>>() {},\n" + "    new $L()\n" + ")",
						ClassName.get(com.google.common.reflect.TypeToken.class), dtoClassName,
						ClassName.get(com.google.common.reflect.TypeToken.class),
						ClassName.get(com.google.common.reflect.TypeToken.class), operationsClass, className,
						fieldsClass)
				.build();

		classBuilder.addMethod(constructor);

		return classBuilder.build();
	}
}
