package dukono.minidsl.processor.generator;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;
import java.util.function.UnaryOperator;

/**
 * Generates the AnchorActions class for a DSL domain. Provides action
 * operations like replace, modify, and remove.
 */
public class AnchorActionsGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final TypeSpec typeSpec = this.generateAsNestedClass(context);

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = "AnchorActions";
		final String fieldsClassName = "Fields";
		final String operationsLogicalClassName = "AnchorOperationsLogical";
		final String anchorOneClassName = "AnchorOne";
		final String anchorListClassName = "AnchorList";
		final String anchorClassName = "AnchorMain";
		final String anchorLogicalMainClassName = "AnchorLogicalMain";
		final String dtoClassName = "Dto";

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.superclass(ParameterizedTypeName.get(ClassName.get("dukono.minidsl", "AnchorHolderMainActions"),
						ClassName.bestGuess(fieldsClassName), ClassName.bestGuess(dtoClassName),
						ClassName.bestGuess(className),
						ParameterizedTypeName.get(ClassName.bestGuess(operationsLogicalClassName),
								ClassName.bestGuess(className))))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorActions class for $L domain.\n", context.getDomainName())
				.addJavadoc("Provides action operations like replace, modify, and remove.\n")
				.addJavadoc("\n@generated by DslProcessor\n");

		// Default constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super(new $T<$L>() {}, new $T<$L<?>>() {}, new $T<$L<$L>>() {}, new $L())",
						ClassName.get("com.google.common.reflect", "TypeToken"), dtoClassName,
						ClassName.get("com.google.common.reflect", "TypeToken"), anchorListClassName,
						ClassName.get("com.google.common.reflect", "TypeToken"), operationsLogicalClassName, className,
						fieldsClassName)
				.build();

		// Constructor with DTO
		final MethodSpec constructorWithDto = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addParameter(ClassName.bestGuess(dtoClassName), "dto").addStatement("this()")
				.addStatement("this.dtoClazzInstance = java.util.Optional.ofNullable(dto)").build();

		// Constructor with collection
		final MethodSpec constructorWithCollection = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addParameter(ParameterizedTypeName.get(ClassName.get(Collection.class), ClassName.get(String.class)),
						"dtoData")
				.addStatement("this()").addStatement("this.getDto().parseFilters(dtoData)").build();

		// listCollapseAnd method
		final TypeVariableName l = TypeVariableName.get("L");
		final MethodSpec listCollapseAnd = MethodSpec.methodBuilder("listCollapseAnd").addModifiers(Modifier.PUBLIC)
				.addTypeVariable(l).returns(ClassName.bestGuess(className))
				.addParameter(ParameterizedTypeName.get(ClassName.get(List.class), l), "list")
				.addParameter(ParameterizedTypeName.get(ClassName.get(UnaryOperator.class),
						ParameterizedTypeName.get(ClassName.bestGuess(anchorOneClassName), l)), "operator")
				.addStatement("return super.collapse(list, operator, $T.AND)", ClassName.get("dukono.minidsl", "Query"))
				.build();

		// listCollapseOr method
		final MethodSpec listCollapseOr = MethodSpec.methodBuilder("listCollapseOr").addModifiers(Modifier.PUBLIC)
				.addTypeVariable(l).returns(ClassName.bestGuess(className))
				.addParameter(ParameterizedTypeName.get(ClassName.get(List.class), l), "list")
				.addParameter(ParameterizedTypeName.get(ClassName.get(UnaryOperator.class),
						ParameterizedTypeName.get(ClassName.bestGuess(anchorOneClassName), l)), "operator")
				.addStatement("return super.collapse(list, operator, $T.OR)", ClassName.get("dukono.minidsl", "Query"))
				.build();

		// listAddForEach method
		final MethodSpec listAddForEach = MethodSpec.methodBuilder("listAddForEach").addModifiers(Modifier.PUBLIC)
				.addTypeVariable(l).returns(ClassName.bestGuess(className))
				.addParameter(ParameterizedTypeName.get(ClassName.get(List.class), l), "list")
				.addParameter(ParameterizedTypeName.get(ClassName.get(UnaryOperator.class),
						ParameterizedTypeName.get(ClassName.bestGuess(anchorOneClassName), l)), "operator")
				.addStatement("return super.notCollapse(list, operator)").build();

		// replace method
		final MethodSpec replace = MethodSpec.methodBuilder("replace").addModifiers(Modifier.PUBLIC)
				.returns(ClassName.bestGuess(className))
				.addParameter(ParameterizedTypeName.get(ClassName.get(UnaryOperator.class),
						ClassName.bestGuess(anchorLogicalMainClassName)), "toFind")
				.addParameter(ParameterizedTypeName.get(ClassName.get(UnaryOperator.class),
						ClassName.bestGuess(anchorLogicalMainClassName)), "newValue")
				.addStatement("return super.replace(toFind, newValue, new $T<$L>() {})",
						ClassName.get("com.google.common.reflect", "TypeToken"), anchorLogicalMainClassName)
				.build();

		// modify method
		final MethodSpec modify = MethodSpec.methodBuilder("modify").addModifiers(Modifier.PUBLIC)
				.returns(ClassName.bestGuess(className))
				.addParameter(ParameterizedTypeName.get(ClassName.get(UnaryOperator.class),
						ClassName.bestGuess(anchorLogicalMainClassName)), "change")
				.addParameter(ParameterizedTypeName.get(ClassName.get(Function.class),
						ClassName.get("dukono.minidsl", "Comparator"),
						ClassName.get("dukono.minidsl", "ComparatorEnum")), "comparatorFunction")
				.addStatement("return super.modify(change, comparatorFunction, new $T<$L>() {})",
						ClassName.get("com.google.common.reflect", "TypeToken"), anchorLogicalMainClassName)
				.build();

		// remove method
		final MethodSpec remove = MethodSpec.methodBuilder("remove").addModifiers(Modifier.PUBLIC)
				.returns(ClassName.bestGuess(className))
				.addParameter(ParameterizedTypeName.get(ClassName.get(Function.class),
						ParameterizedTypeName.get(ClassName.get("dukono.minidsl", "RemoveBy"),
								ClassName.bestGuess(anchorClassName), ClassName.bestGuess(anchorLogicalMainClassName)),
						ClassName.get("dukono.minidsl", "RemoveBy", "Remover")), "removeFunction")
				.addStatement("return super.remove(removeFunction, new $T<$L>() {}, new $T<$L>() {})",
						ClassName.get("com.google.common.reflect", "TypeToken"), anchorClassName,
						ClassName.get("com.google.common.reflect", "TypeToken"), anchorLogicalMainClassName)
				.build();

		classBuilder.addMethod(constructor);
		classBuilder.addMethod(constructorWithDto);
		classBuilder.addMethod(constructorWithCollection);
		classBuilder.addMethod(listCollapseAnd);
		classBuilder.addMethod(listCollapseOr);
		classBuilder.addMethod(listAddForEach);
		classBuilder.addMethod(replace);
		classBuilder.addMethod(modify);
		classBuilder.addMethod(remove);

		return classBuilder.build();
	}
}
