package dukono.minidsl.processor.generator;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import com.squareup.javapoet.WildcardTypeName;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.Collection;
import java.util.function.Function;

/**
 * Generates the AnchorOperationsOne class for a DSL domain. Used for operations
 * on individual items within lists.
 */
public class AnchorOperationsOneGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String className = context.getDomainName() + "AnchorOperationsOne";
		final String logicalClassName = context.getDomainName() + "AnchorOperationsLogical";

		// Type variables
		final TypeVariableName h = TypeVariableName.get("H",
				ParameterizedTypeName.get(ClassName.get("dukono.minidsl", "AnchorHolderOne"),
						WildcardTypeName.subtypeOf(Object.class), WildcardTypeName.subtypeOf(Object.class),
						TypeVariableName.get("H"), TypeVariableName.get("O"),
						WildcardTypeName.subtypeOf(Object.class)));
		final TypeVariableName o = TypeVariableName.get("O");

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC)
				.addTypeVariable(h).addTypeVariable(o)
				.superclass(ParameterizedTypeName.get(ClassName.get(context.getPackageName(), logicalClassName),
						TypeVariableName.get("H")))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorOperationsOne class for $L domain.\n", context.getDomainName())
				.addJavadoc("Operations for individual items within lists using Function extractors.\n")
				.addJavadoc("\n@generated by DslProcessor\n");

		// Generate methods for each operation that accepts Function
		classBuilder.addMethod(this.generateFunctionMethod("equalTo", "eq", false));
		classBuilder.addMethod(this.generateFunctionMethod("notEqualTo", "ne", false));
		classBuilder.addMethod(this.generateFunctionMethod("greaterThan", "gt", false));
		classBuilder.addMethod(this.generateFunctionMethod("greaterThanOrEqual", "gte", false));
		classBuilder.addMethod(this.generateFunctionMethod("lessThan", "lt", false));
		classBuilder.addMethod(this.generateFunctionMethod("lessThanOrEqual", "lte", false));
		classBuilder.addMethod(this.generateFunctionMethod("like", "like", false));
		classBuilder.addMethod(this.generateFunctionMethod("inValues", "in", true));

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	private MethodSpec generateFunctionMethod(final String methodName, final String operator,
			final boolean isCollection) {
		final MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(methodName).addModifiers(Modifier.PUBLIC)
				.returns(TypeVariableName.get("H"));

		if (isCollection) {
			// Collection parameter: Function<O, Collection<?>>
			methodBuilder.addParameter(ParameterizedTypeName.get(ClassName.get(Function.class),
					TypeVariableName.get("O"), ParameterizedTypeName.get(ClassName.get(Collection.class),
							WildcardTypeName.subtypeOf(Object.class))),
					"extractor");
			methodBuilder.addStatement(
					"return this.create($T.from(this.getName(), $S, this.listFormatting(extractor.apply(this.holder.getItemUnit()))))",
					ClassName.get("dukono.minidsl", "Query"), operator);
		} else {
			// Single value parameter: Function<O, Object>
			methodBuilder.addParameter(ParameterizedTypeName.get(ClassName.get(Function.class),
					TypeVariableName.get("O"), ClassName.get(Object.class)), "extractor");
			methodBuilder.addStatement(
					"return this.create($T.from(this.getName(), $S, extractor.apply(this.holder.getItemUnit())))",
					ClassName.get("dukono.minidsl", "Query"), operator);
		}

		return methodBuilder.build();
	}
}
