package dukono.minidsl.processor.generator;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the AnchorOne class for a DSL domain. Used for individual items
 * within lists.
 */
public class AnchorOneGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final TypeSpec typeSpec = this.generateAsNestedClass(context);

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = GeneratedClassNames.ANCHOR_ONE.getClassName();
		final String fieldsClassName = GeneratedClassNames.FIELDS.getClassName();
		final String operationsOneClassName = GeneratedClassNames.ANCHOR_OPERATIONS_ONE.getClassName();
		final ClassName dtoClassName = context.getDtoClassName();

		final TypeVariableName t = TypeVariableName.get("T");

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).addTypeVariable(t)
				.superclass(
						ParameterizedTypeName.get(ClassName.get(dukono.minidsl.AnchorHolderOne.class),
								ClassName.bestGuess(fieldsClassName), dtoClassName,
								ParameterizedTypeName.get(ClassName.bestGuess(className), TypeVariableName.get("T")),
								TypeVariableName.get("T"),
								ParameterizedTypeName.get(ClassName.bestGuess(operationsOneClassName),
										ParameterizedTypeName.get(ClassName.bestGuess(className),
												TypeVariableName.get("T")),
										TypeVariableName.get("T"))))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorOne class for $L domain.\n", context.getDomainName())
				.addJavadoc("Represents a single item within a list for DSL operations.\n")
				.addJavadoc("\n@param <T> the type of the list item\n").addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super(new $T<$T>() {}, new $L(), new $T<$L<$L<T>, T>>() {})",
						ClassName.get(com.google.common.reflect.TypeToken.class), dtoClassName, fieldsClassName,
						ClassName.get(com.google.common.reflect.TypeToken.class), operationsOneClassName, className)
				.build();

		classBuilder.addMethod(constructor);

		return classBuilder.build();
	}
}
