package dukono.minidsl.processor.generator;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the AnchorList class for a DSL domain. Used for list operations.
 */
public class AnchorListGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String className = context.getDomainName() + GeneratedClassNames.ANCHOR_LIST.getClassName();
		final String fieldsClassName = context.getFieldsClassName();
		final String anchorOneClassName = context.getDomainName() + GeneratedClassNames.ANCHOR_ONE.getClassName();
		final String anchorLogicalMainClassName = context.getDomainName()
				+ GeneratedClassNames.ANCHOR_LOGICAL_MAIN.getClassName();
		final String dtoClassName = context.getDtoClass();

		final TypeVariableName t = TypeVariableName.get("T");

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC)
				.addTypeVariable(t)
				.superclass(ParameterizedTypeName.get(ClassName.get(dukono.minidsl.AnchorHolderList.class),
						ClassName.get(context.getPackageName(), fieldsClassName),
						ParameterizedTypeName.get(ClassName.get(context.getPackageName(), anchorOneClassName),
								TypeVariableName.get("T")),
						ClassName.get(context.getPackageName(), anchorLogicalMainClassName),
						ClassName.bestGuess(dtoClassName),
						ParameterizedTypeName.get(ClassName.get(context.getPackageName(), className),
								TypeVariableName.get("T")),
						TypeVariableName.get("T")))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorList class for $L domain.\n", context.getDomainName())
				.addJavadoc("Handles list operations in the DSL.\n").addJavadoc("\n@param <T> the type of list items\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super(new $T<>() {}, $T.class)",
						ClassName.get(com.google.common.reflect.TypeToken.class),
						ClassName.get(context.getPackageName(), anchorLogicalMainClassName))
				.build();

		classBuilder.addMethod(constructor);

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = GeneratedClassNames.ANCHOR_LIST.getClassName();
		final String fieldsClassName = GeneratedClassNames.FIELDS.getClassName();
		final String anchorOneClassName = GeneratedClassNames.ANCHOR_ONE.getClassName();
		final String anchorLogicalMainClassName = GeneratedClassNames.ANCHOR_LOGICAL_MAIN.getClassName();
		final ClassName dtoClassName = context.getDtoClassName();

		final TypeVariableName t = TypeVariableName.get("T");

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).addTypeVariable(t)
				.superclass(ParameterizedTypeName.get(ClassName.get(dukono.minidsl.AnchorHolderList.class),
						ClassName.bestGuess(fieldsClassName),
						ParameterizedTypeName.get(ClassName.bestGuess(anchorOneClassName), TypeVariableName.get("T")),
						ClassName.bestGuess(anchorLogicalMainClassName), dtoClassName,
						ParameterizedTypeName.get(ClassName.bestGuess(className), TypeVariableName.get("T")),
						TypeVariableName.get("T")))
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addJavadoc("Generated AnchorList class for $L domain.\n", context.getDomainName())
				.addJavadoc("Handles list operations in the DSL.\n").addJavadoc("\n@param <T> the type of list items\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super(new $T<>() {}, $L.class)",
						ClassName.get(com.google.common.reflect.TypeToken.class), anchorLogicalMainClassName)
				.build();

		classBuilder.addMethod(constructor);

		return classBuilder.build();
	}
}
