package dukono.minidsl.processor.generator;

import com.squareup.javapoet.*;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the AnchorMain class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public class VehicleAnchor
 * 		extends
 * 			AnchorHolderMainActions<VehicleFields, DtoString, VehicleAnchor, VehicleAnchorOperations<VehicleAnchor>> {
 * 
 * 	public VehicleAnchor() {
 * 		super(new TypeToken<DtoString>() {
 * 		}, new TypeToken<VehicleList<?>>() {
 * 		}, new TypeToken<VehicleAnchor>() {
 * 		}, new TypeToken<VehicleAnchorOperations<VehicleAnchor>>() {
 * 		}, new VehicleFields());
 * 	}
 * }
 * </pre>
 */
public class AnchorMainGenerator {

	public void generate(DslContext context, Filer filer) throws IOException {
		String className = context.getAnchorClassName();
		String fieldsClass = context.getFieldsClassName();
		String operationsClass = context.getAnchorOperationsClassName();
		String dtoClass = context.getDtoSimpleName();

		// Determine base class based on configuration
		ClassName baseClass;
		if (context.isWithActions()) {
			baseClass = ClassName.get("dukono.minidsl", "AnchorHolderMainActions");
		} else if (context.isWithLogical()) {
			baseClass = ClassName.get("dukono.minidsl", "AnchorHolderMainLogical");
		} else {
			baseClass = ClassName.get("dukono.minidsl", "AnchorHolderMain");
		}

		ClassName anchorClassName = ClassName.get(context.getPackageName(), className);

		TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC)
				.superclass(ParameterizedTypeName.get(baseClass, ClassName.get(context.getPackageName(), fieldsClass),
						ClassName.get("dukono.minidsl", dtoClass), anchorClassName,
						ParameterizedTypeName.get(ClassName.get(context.getPackageName(), operationsClass),
								anchorClassName)))
				.addJavadoc("Generated Anchor class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("This is the main entry point for building queries.\n").addJavadoc("\n")
				.addJavadoc("Example:\n").addJavadoc("<pre>\n").addJavadoc("new $L()\n", className)
				.addJavadoc("    .field(f -> f.FIELD_NAME).equalTo(value)\n").addJavadoc("    .other()\n")
				.addJavadoc("    .getDto();\n").addJavadoc("</pre>\n").addJavadoc("\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Constructor
		MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC).addStatement(
				"super(\n" + "    new $T<$T>() {},\n" + "    new $T<$LAnchorList<?>>() {},\n" + "    new $T<$T>() {},\n"
						+ "    new $T<$T<$T>>() {},\n" + "    new $T()\n" + ")",
				ClassName.get("com.google.common.reflect", "TypeToken"), ClassName.get("dukono.minidsl", dtoClass),
				ClassName.get("com.google.common.reflect", "TypeToken"), context.getDomainName(),
				ClassName.get("com.google.common.reflect", "TypeToken"), anchorClassName,
				ClassName.get("com.google.common.reflect", "TypeToken"),
				ClassName.get(context.getPackageName(), operationsClass), anchorClassName,
				ClassName.get(context.getPackageName(), fieldsClass)).build();

		classBuilder.addMethod(constructor);

		// Constructor with DTO
		MethodSpec constructorWithDto = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addParameter(ClassName.get("dukono.minidsl", dtoClass), "dto").addStatement("this()")
				.addStatement("this.dto = dto").addJavadoc("Constructor with existing DTO.\n").addJavadoc("\n")
				.addJavadoc("@param dto the DTO to use\n").build();

		classBuilder.addMethod(constructorWithDto);

		TypeSpec typeSpec = classBuilder.build();

		JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}
}
