package dukono.minidsl.processor.generator;

import com.squareup.javapoet.*;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the Api factory class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public final class VehicleApi {
 * 	private VehicleApi() {
 * 	}
 * 
 * 	public static VehicleAnchor from() {
 * 		return new VehicleAnchor();
 * 	}
 * 
 * 	public static VehicleAnchor from(DtoString dto) {
 * 		return new VehicleAnchor(dto);
 * 	}
 * }
 * </pre>
 */
public class ApiGenerator {

	public void generate(DslContext context, Filer filer) throws IOException {
		String className = context.getApiClassName();
		String anchorClass = context.getAnchorClassName();
		String dtoClass = context.getDtoSimpleName();

		ClassName anchorClassName = ClassName.get(context.getPackageName(), anchorClass);
		ClassName dtoClassName = ClassName.get("dukono.minidsl", dtoClass);

		TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addJavadoc("Generated Api factory class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("Provides static factory methods for creating DSL instances.\n").addJavadoc("\n")
				.addJavadoc("Example:\n").addJavadoc("<pre>\n").addJavadoc("$L.from()\n", className)
				.addJavadoc("    .field(f -> f.FIELD_NAME).equalTo(value)\n").addJavadoc("    .other();\n")
				.addJavadoc("</pre>\n").addJavadoc("\n").addJavadoc("@generated by DslProcessor\n");

		// Private constructor
		MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE)
				.addJavadoc("Private constructor to prevent instantiation.\n").build();
		classBuilder.addMethod(constructor);

		// from() method
		MethodSpec fromMethod = MethodSpec.methodBuilder("from").addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.returns(anchorClassName).addStatement("return new $T()", anchorClassName)
				.addJavadoc("Creates a new DSL instance.\n").addJavadoc("\n")
				.addJavadoc("@return a new $L instance\n", anchorClass).build();
		classBuilder.addMethod(fromMethod);

		// from(dto) method
		MethodSpec fromDtoMethod = MethodSpec.methodBuilder("from").addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.returns(anchorClassName).addParameter(dtoClassName, "dto")
				.addStatement("return new $T(dto)", anchorClassName)
				.addJavadoc("Creates a new DSL instance with an existing DTO.\n").addJavadoc("\n")
				.addJavadoc("@param dto the DTO to use\n").addJavadoc("@return a new $L instance\n", anchorClass)
				.build();
		classBuilder.addMethod(fromDtoMethod);

		TypeSpec typeSpec = classBuilder.build();

		JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}
}
