package dukono.minidsl.processor.generator;

import java.io.IOException;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import dukono.minidsl.processor.DslContext;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;

/**
 * Generates the Api factory class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public final class VehicleApi {
 * 	private VehicleApi() {
 * 	}
 * 
 * 	public static VehicleAnchor from() {
 * 		return new VehicleAnchor();
 * 	}
 * 
 * 	public static VehicleAnchor from(DtoString dto) {
 * 		return new VehicleAnchor(dto);
 * 	}
 * }
 * </pre>
 */
public class ApiGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String className = context.getApiClassName();

		// Always use AnchorActions (since all classes are generated)
		final String anchorClass = context.getDomainName() + "AnchorActions";

		final ClassName anchorClassName = ClassName.get(context.getPackageName(), anchorClass);
		final ClassName dtoClassName = ClassName.get(context.getDtoPackageName(), context.getDtoSimpleName());

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addJavadoc("Generated Api factory class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("Provides static factory methods for creating DSL instances.\n").addJavadoc("\n")
				.addJavadoc("Example:\n").addJavadoc("<pre>\n").addJavadoc("$L.from()\n", className)
				.addJavadoc("    .field(f -> f.FIELD_NAME).equalTo(value)\n").addJavadoc("    .other();\n")
				.addJavadoc("</pre>\n").addJavadoc("\n").addJavadoc("@generated by DslProcessor\n");

		// Private constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE)
				.addJavadoc("Private constructor to prevent instantiation.\n").build();
		classBuilder.addMethod(constructor);

		// from() method
		final MethodSpec fromMethod = MethodSpec.methodBuilder("from").addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.returns(anchorClassName).addStatement("return new $T()", anchorClassName)
				.addJavadoc("Creates a new DSL instance.\n").addJavadoc("\n")
				.addJavadoc("@return a new $L instance\n", anchorClass).build();
		classBuilder.addMethod(fromMethod);

		// from(dto) method
		final MethodSpec fromDtoMethod = MethodSpec.methodBuilder("from").addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.returns(anchorClassName).addParameter(dtoClassName, "dto")
				.addStatement("return new $T(dto)", anchorClassName)
				.addJavadoc("Creates a new DSL instance with an existing DTO.\n").addJavadoc("\n")
				.addJavadoc("@param dto the DTO to use\n").addJavadoc("@return a new $L instance\n", anchorClass)
				.build();
		classBuilder.addMethod(fromDtoMethod);

		// from(Collection<String>) method - always generated since Actions is always
		// included
		final MethodSpec fromCollectionMethod = MethodSpec.methodBuilder("from")
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).returns(anchorClassName)
				.addParameter(ParameterizedTypeName.get(ClassName.get(java.util.Collection.class),
						ClassName.get(String.class)), "queries")
				.addStatement("return new $T(queries)", anchorClassName)
				.addJavadoc("Creates a new DSL instance with predefined queries.\n").addJavadoc("\n")
				.addJavadoc("@param queries the collection of queries to parse\n")
				.addJavadoc("@return a new $L instance\n", anchorClass).build();
		classBuilder.addMethod(fromCollectionMethod);

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}
}
