package dukono.minidsl.processor.generator;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the DTO class that extends dukono.minidsl.Dto.
 * 
 * The DTO class contains a Map<String, Object> to store field values and
 * provides getter/setter methods for each field.
 * 
 * Example generated code:
 * 
 * <pre>
 * public class OrderDto extends Dto {
 * 	public OrderDto() {
 * 		super();
 * 	}
 * 
 * 	public String getOrderId() {
 * 		return (String) this.get("orderId");
 * 	}
 * 
 * 	public void setOrderId(String value) {
 * 		this.put("orderId", value);
 * 	}
 * }
 * </pre>
 */
public class DtoGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String dtoSimpleName = context.getDtoSimpleName();
		final String dtoPackageName = context.getDtoPackageName();

		final ClassName dtoBaseClass = ClassName.get("dukono.minidsl", "Dto");

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(dtoSimpleName).addModifiers(Modifier.PUBLIC)
				.superclass(dtoBaseClass).addJavadoc("Generated DTO class for $L domain.\n", context.getDomainName())
				.addJavadoc("\n").addJavadoc("Extends {@link dukono.minidsl.Dto} which provides a Map-based storage.\n")
				.addJavadoc("\n").addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super()").addJavadoc("Creates a new empty DTO instance.\n").build();
		classBuilder.addMethod(constructor);

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(dtoPackageName, typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	/**
	 * Converts UPPER_SNAKE_CASE or snake_case to CamelCase. Examples: - ORDER_ID ->
	 * OrderId - customer_name -> CustomerName - STATUS -> Status
	 */
	private String toCamelCase(final String input) {
		if (input == null || input.isEmpty()) {
			return input;
		}

		final String[] parts = input.split("_");
		final StringBuilder result = new StringBuilder();

		for (final String part : parts) {
			if (!part.isEmpty()) {
				result.append(Character.toUpperCase(part.charAt(0)));
				if (part.length() > 1) {
					result.append(part.substring(1).toLowerCase());
				}
			}
		}

		return result.toString();
	}
}
