package dukono.minidsl.processor.generator;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the DTO class that extends dukono.minidsl.Dto.
 * 
 * The DTO class contains a Map<String, Object> to store field values and
 * provides getter/setter methods for each field.
 * 
 * Example generated code:
 * 
 * <pre>
 * public class OrderDto extends Dto {
 * 	public OrderDto() {
 * 		super();
 * 	}
 * 
 * 	public String getOrderId() {
 * 		return (String) this.get("orderId");
 * 	}
 * 
 * 	public void setOrderId(String value) {
 * 		this.put("orderId", value);
 * 	}
 * }
 * </pre>
 */
public class DtoGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final TypeSpec typeSpec = this.generateAsNestedClass(context);

		final JavaFile javaFile = JavaFile.builder(context.getDtoPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		// Use the simple name from context (e.g., "OrderDto", "UserDto")
		final String dtoSimpleName = context.getDtoSimpleName();

		final ClassName dtoBaseClass = ClassName.get(dukono.minidsl.Dto.class);

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(dtoSimpleName)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).superclass(dtoBaseClass)
				.addJavadoc("Generated DTO class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("Extends {@link dukono.minidsl.Dto} which provides a Map-based storage.\n").addJavadoc("\n")
				.addJavadoc("This DTO is auto-generated because no dtoClass was specified in @DslDomain.\n")
				.addJavadoc("\n").addJavadoc("@generated by DslProcessor\n");

		// Constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC)
				.addStatement("super()").addJavadoc("Creates a new empty DTO instance.\n").build();
		classBuilder.addMethod(constructor);

		return classBuilder.build();
	}
}
