package dukono.minidsl.processor.generator;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;
import dukono.minidsl.annotation.DslField;
import dukono.minidsl.processor.DslContext;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the Fields class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public class VehicleFields extends Field {
 * 	public final FieldHolder MARCA = Field.from("MARCA");
 * 	public final FieldHolder YEAR = Field.from("YEAR");
 * }
 * </pre>
 */
public class FieldsGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final TypeSpec typeSpec = this.generateAsNestedClass(context);

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	public TypeSpec generateAsNestedClass(final DslContext context) {
		final String className = "Fields";

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC).superclass(ClassName.get(dukono.minidsl.Field.class))
				.addJavadoc("Generated Fields class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("Use with: {@code .field(f -> f.FIELDNAME)}\n").addJavadoc("\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Add fields
		for (final DslField field : context.getFields()) {
			final String fieldName = field.javaName();
			final String fieldValue = field.value();

			FieldSpec fieldSpec = FieldSpec
					.builder(ClassName.get(dukono.minidsl.Field.FieldHolder.class), fieldName, Modifier.PUBLIC,
							Modifier.FINAL)
					.initializer("$T.from($S)", ClassName.get(dukono.minidsl.Field.class), fieldValue).build();

			if (!field.description().isEmpty()) {
				fieldSpec = fieldSpec.toBuilder().addJavadoc("$L\n", field.description()).build();
			}

			classBuilder.addField(fieldSpec);
		}

		return classBuilder.build();
	}
}
