package dukono.minidsl.processor.generator;

import java.io.IOException;

import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import dukono.minidsl.annotation.DslOperation;
import dukono.minidsl.processor.DslContext;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;

/**
 * Generates the Operations class for a DSL domain.
 * 
 * Example generated code:
 * 
 * <pre>
 * public final class VehicleOperations {
 * 	private VehicleOperations() {
 * 	}
 * 
 * 	public static final String EQ = "eq";
 * 	public static final String GT = "gt";
 * }
 * </pre>
 */
public class OperationsGenerator {

	public void generate(final DslContext context, final Filer filer) throws IOException {
		final String className = context.getOperationsClassName();

		final TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addJavadoc("Generated Operations class for $L domain.\n", context.getDomainName()).addJavadoc("\n")
				.addJavadoc("Contains all operation constants used by the DSL.\n").addJavadoc("\n")
				.addJavadoc("@generated by DslProcessor\n");

		// Private constructor
		final MethodSpec constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE)
				.addJavadoc("Private constructor to prevent instantiation.\n").build();
		classBuilder.addMethod(constructor);

		// Add operation constants
		for (final DslOperation operation : context.getOperations()) {
			final String constantName = this.toConstantName(operation.operator());
			final String operatorValue = operation.operator();

			FieldSpec fieldSpec = FieldSpec
					.builder(String.class, constantName, Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
					.initializer("$S", operatorValue).build();

			if (!operation.description().isEmpty()) {
				fieldSpec = fieldSpec.toBuilder().addJavadoc("$L\n", operation.description()).build();
			}

			classBuilder.addField(fieldSpec);
		}

		final TypeSpec typeSpec = classBuilder.build();

		final JavaFile javaFile = JavaFile.builder(context.getPackageName(), typeSpec)
				.addFileComment("Generated by Mini-DSL Processor")
				.addFileComment("\nDO NOT EDIT - This file is auto-generated").build();

		javaFile.writeTo(filer);
	}

	private String toConstantName(final String operator) {
		// Convert "eq" -> "EQ", "is_not_null" -> "IS_NOT_NULL"
		return operator.toUpperCase().replace('-', '_');
	}
}
